version: "3.8"
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  api:
    build: ./backend
    container_name: nutrition-api
    restart: unless-stopped
    environment:
      - PORT=5000
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=llama3.2
      - NODE_ENV=production
    depends_on:
      - ollama
    ports:
      - "5000:5000"

  web:
    build: ./frontend
    container_name: nutrition-web
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "3000:80"

volumes:
  ollama_data:
